### ISSUE TITLE
WASM too big

### ISSUE THREAD

**Issue by datased2019** [EdwardLu2018/wasm-ar#11]
The img_tracker_wasm.wasm is very big for loading. How to reduce the size of it?

**Comment by kalwalt** [comment]
> The img_tracker_wasm.wasm is very big for loading. How to reduce the size of it?

@datased2019 yes i think it can be optimized. Actually it preserve debug informations. You can try to rebuild the lib without these [flags](https://github.com/EdwardLu2018/wasm-ar/blob/76b749b48c8170fda9d2de3c1f85d98b40c46a98/CMakeLists.txt#L10) using instead: 

`set( CMAKE_CXX_FLAGS_RELEASE " -Oz" )`
and in https://github.com/EdwardLu2018/wasm-ar/blob/76b749b48c8170fda9d2de3c1f85d98b40c46a98/CMakeLists.txt#L33
delete the `-s ASSERTIONS=1`. The resulting code should be smaller and optimized. I haven't tried so i can't assure it.

**Comment by EdwardLu2018** [comment]
Yes, I can definitely try to shrink the wasm binary.

**Comment by EdwardLu2018** [comment]
Removed debug flags in https://github.com/EdwardLu2018/wasm-ar/commit/db376bf73b63b85a3938b4c36ee5d95d72f76618. Still seems a bit large. Will the `-Oz` optimization flag reduce performance?

**Comment by kalwalt** [comment]
i tried to build with the `-Oz` flag: the **img_tracker_wasm.wasm** code is 1.7 mb in size in contrary with the `-g -Wall -O3` flag is 5.1mb. It shouldn't affect performance but it is required some tests.

**Comment by datased2019** [comment]
@kalwalt  Great job. 1.7mb much better.

**Comment by datased2019** [comment]
![image](https://user-images.githubusercontent.com/48910575/135057175-210d80e0-5477-4180-b75a-1b820cfbcb75.png)
