### ISSUE TITLE
Prevent name mangling in initAR, track and resetTracking

### ISSUE THREAD

**Issue by kalwalt** [EdwardLu2018/wasm-ar#12]
The functions initAR, track and resetTracking are invoked with an Emscripten `cwrap` function with mangled names for example initAR is invoked with https://github.com/EdwardLu2018/wasm-ar/blob/76b749b48c8170fda9d2de3c1f85d98b40c46a98/js/image-tracker.js#L22 note `"_Z6initARPhmm"` that happens because the three functions are not wrapped inside a 
```c++
extern "C" {
 } 
```
to prevent C++ name mangling as described in https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html?highlight=cwrap#calling-compiled-c-functions-from-javascript-using-ccall-cwrap and add those function to the `-s EXPORTED_FUNCTIONS='['_malloc', '_free', '_initAR', '_track', '_resetTracking']'`
@EdwardLu2018 I would submit a PR if you agree.

**Comment by EdwardLu2018** [comment]
Ohhh, I see. Thanks for pointing this out, feel free to make a PR for this!

**Comment by EdwardLu2018** [comment]
Added this in https://github.com/EdwardLu2018/wasm-ar/commit/db376bf73b63b85a3938b4c36ee5d95d72f76618

**Comment by kalwalt** [comment]
@EdwardLu2018 Does it works? Without adding `-s EXPORTED_FUNCTIONS='['_malloc', '_free', '_initAR', '_track', '_resetTracking']'` ?

**Comment by EdwardLu2018** [comment]
It should, because I had `EMSCRIPTEN_KEEPALIVE` before each of those exported function definitions. I believe it still works

**Comment by kalwalt** [comment]
> It should, because I had `EMSCRIPTEN_KEEPALIVE` before each of those exported function definitions. I believe it still works

Ok i will test your changes :smiley:

**Comment by kalwalt** [comment]
You are right, It's not necessary. we can close this.

**Comment by datased2019** [comment]
I have encounter the problem after compiled. Any Comments?
![image](https://user-images.githubusercontent.com/48910575/135070258-e92a1c54-299d-4707-9cf1-ce004d373ad3.png)

**Comment by kalwalt** [comment]
> I have encounter the problem after compiled. Any Comments? ![image](https://user-images.githubusercontent.com/48910575/135070258-e92a1c54-299d-4707-9cf1-ce004d373ad3.png)

It could depends by which emcc version are you used to build the libs, I have used emcc 2.0.20 version, consider that previous version may have slightly differences. Have you also run the `npm run build` command?

**Comment by EdwardLu2018** [comment]
Maybe try cleaning your build folder or your browser cache? @kalwalt Does the latest version work for you?

**Comment by kalwalt** [comment]
> Maybe try cleaning your build folder or your browser cache? @kalwalt Does the latest version work for you?

@EdwardLu2018 I will check again when i have time. :smile:

**Comment by datased2019** [comment]
I just follow the install steps and get emsdk 1.39.16 activated. It seems the FUNCTIONS are not exported correctly.

**Comment by datased2019** [comment]
Sorry. My bad. I just got some files changed and didn't notice that. It's working. Pls close it. Thx.
