### ISSUE TITLE
Questions about building the project

### ISSUE THREAD

**Issue by kalwalt** [EdwardLu2018/wasm-ar#2]
I read in the [Readme.md](https://github.com/EdwardLu2018/wasm-ar/Readme.md) that is necessary to build the openCV lib but which version do you used? Can you specify the version? It will be very useful for testing... :smile:

**Comment by kalwalt** [comment]
i was able to build the project with the instructions in #3 feel free to acccept it or not if you don't agree :slightly_smiling_face:

**Comment by EdwardLu2018** [comment]
Yep! Looks great! I definitely need to have more documentation and possibly more comments in various places. Thanks!
Probably already found this out, but just in case, I used OpenCV 3!

**Comment by kalwalt** [comment]
Thank you it is a pleasure!

**Comment by kalwalt** [comment]
BTW, i used tha latest openCV with latest from master branch, It compiled and build all the static libs, but failed to build the OpenCV.js, anyway this was sufficient to complete, i will try with the latest release [4.5.0](https://github.com/opencv/opencv/releases/tag/4.5.0) :smile:

**Comment by EdwardLu2018** [comment]
Hmm interesting. Seems to build fine with opencv master on my machine. 
What version is your emsdk? Mine is an older-ish version (819e95c).

**Comment by kalwalt** [comment]
I have used a recent emsdk version: 2.0.8 see the log:
```
./emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.8
clang version 12.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 1a7a9efec3cf872dcf3e1a6e6fe39e797c4d9fc6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/walter/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

```
The default version is based on `upstream`,  it gives smaller size of the build and many other improves. To avoid different builds ( because developers use different version) while developing for jsartoolkit5 we start to use the emscripten Docker image, the `trzeci` but now is deprecated (very old and fastcomp based). There is now the Docker image by emsdk, but i never tried...

**Comment by EdwardLu2018** [comment]
Hmmm... Seems like the version of emscripten recommended by opencv is 1.39.16
```
./emsdk update
./emsdk install 1.39.16
./emsdk activate 1.39.16
```
https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html

**Comment by EdwardLu2018** [comment]
Yeah, I tried a variety of opencv versions that worked in the past and none compiled.
The only thing that worked was rolling emsdk back to 1.39.16

**Comment by kalwalt** [comment]
> Yeah, I tried a variety of opencv versions that worked in the past and none compiled.
> The only thing that worked was rolling emsdk back to 1.39.16

Thank you i will try tomorrow!

**Comment by kalwalt** [comment]
Rolled back to emsdk `1.39.16` and opencv 4.5.0(dev) and it was build with success. :smile: Maybe better stick with the 4.5.0 stable release?

**Comment by EdwardLu2018** [comment]
Sweet!

4.5.0 release should work. I believe I tested it on using that and it compiled fine.
